variable "kubeconfig_path" {
  description = "Path to the Talos cluster's kubeconfig, generated by the proxmox-tofu / talosctl bootstrap."
  type        = string
  default     = "../proxmox-tofu/_out/kubeconfig"
}

variable "namespace" {
  description = "Namespace for the runner and its build/deploy Jobs."
  type        = string
  default     = "ci"
}

variable "ci_hostname" {
  description = "Hostname the runner API will be served on via Ingress. Add this to your workstation's /etc/hosts pointing at a worker node IP, same as every other *.talos.lab host."
  type        = string
  default     = "ci.talos.lab"
}

variable "runner_image" {
  description = "Image repository for the runner itself, pushed to Nexus like every other app's image."
  type        = string
  default     = "registry.talos.lab/ci-runner"
}

variable "runner_image_tag" {
  description = "Image tag to deploy for the runner. Its first build has to be pushed manually (see README) — the pipeline can't build the thing that runs the pipeline."
  type        = string
}

variable "runner_replicas" {
  description = "Replica count for the runner. Kept at 1 — the build queue is in-memory and single-worker, so extra replicas wouldn't coordinate."
  type        = number
  default     = 1
}

variable "nexus_docker_hostname" {
  description = "Hostname for Nexus's docker-hosted repo connector (mirrors cluster-config's variable of the same name, duplicated here to avoid a remote-state read just for a hostname string)."
  type        = string
  default     = "registry.talos.lab"
}

variable "kaniko_image" {
  description = "Kaniko executor image used by build Jobs to build+push images without needing privileged/Docker-in-Docker access (Talos enforces baseline Pod Security Admission cluster-wide, which blocks privileged pods)."
  type        = string
  default     = "gcr.io/kaniko-project/executor:v1.23.2-debug"
}

variable "helm_image" {
  description = "Image with a pinned helm binary, used by deploy Jobs to run `helm upgrade`."
  type        = string
  default     = "alpine/helm:3.16.4"
}

variable "build_workspace_size" {
  description = "Size of the shared ReadWriteMany PVC (on the nfs-csi StorageClass) build Jobs use as scratch space for uploaded source."
  type        = string
  default     = "10Gi"
}

variable "build_job_ttl_seconds" {
  description = "How long finished build/deploy Jobs stick around before Kubernetes garbage-collects them (ttlSecondsAfterFinished) — this is the first repo in this project whose whole job is spawning ephemeral resources repeatedly, so without a TTL the ci namespace accumulates Jobs forever."
  type        = number
  default     = 3600
}

variable "max_concurrent_builds" {
  description = "How many builds the runner will run at once. Kept at 1: worker node talos-c94-oxe (192.168.0.16) is already close to its memory limit ceiling (it runs Nexus), and this is a single-user homelab where nothing needs concurrent builds."
  type        = number
  default     = 1
}

variable "nexus_ci_username" {
  description = "Username for a dedicated Nexus push user for build Jobs (create manually in the Nexus UI — see README; Nexus user creation isn't idempotent so it isn't Terraform-managed here, same reasoning as cluster-config not managing the docker-hosted repo/realm setup)."
  type        = string
  sensitive   = true
}

variable "nexus_ci_password" {
  description = "Password for the Nexus push user above."
  type        = string
  sensitive   = true
}
